image: fudanchii/rails:0.10

services:
  - redis

script:
  - curl -o config/database.yml https://gist.githubusercontent.com/danopia/940155/raw/025d62a8d8102735fade34d52f66f95c3d46e0a6/database.yml
  - bower install --allow-root
  - bundle install --path=/tmp/bundler
  - bundle exec rake test

cache:
  - /tmp/bundler

env:
  - {{secret_token}}

deploy:
  ssh:
    target: {{deploy_host}} {{deploy_port}}
    cmd: {{deploy_cmd}}

notify:
  email:
    recipients:
      - {{notify_email}}
