image: fudanchii/rails:0.9
services:
  - redis
script:
  - curl -o config/database.yml https://gist.githubusercontent.com/danopia/940155/raw/025d62a8d8102735fade34d52f66f95c3d46e0a6/database.yml
  - bower install --allow-root
  - bundle install
  - bundle exec rake test

env:
  - SECRET=thisisasecret
